Repository EaglePhntm/NTFvsAlien, pull requests merged in 2025-06, with the labels that each got.

#247 Expands kz loadout vendor list
  code/__DEFINES/loadout.dm
Labels: Feature

#248 KZ The Fixening
  _maps/map_files/antagmap/antagmap.dmm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/vsd_squad.dm
  code/datums/storage/subtypes/holster.dm
  code/game/objects/items/explosives/grenades/explosive_grenades.dm
  code/game/objects/items/explosives/grenades/phosphorus_grenades.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/mob/clothing/back.dmi
  ntf_modular/code/modules/projectiles/guns/pistols.dm
  ntf_modular/icons/obj/items/storage/holster.dmi
Labels: Fix, Feature

#251 Makes the Cyberghost 50% more effective.
  code/__DEFINES/objects.dm
Labels: Balance

#257 Multi-Hive Improvements
  _maps/map_files/Container/NTF_Container.dmm
  _maps/map_files/NTC_Nine_Tailed_Fox/NTC_Nine_Tailed_Fox - NO Z.dmm
  _maps/map_files/NTC_Nine_Tailed_Fox/NTC_Nine_Tailed_Fox.dmm
  code/__DEFINES/xeno.dm
  code/__HELPERS/game.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/weeds.dm
  code/datums/elements/accelerate_on_cross.dm
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/terragov.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/cocoon.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/resin.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/projectiles/ammo_types/xenos/huggers_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/widow_xenoammo.dm
  code/modules/projectiles/sentries.dm
  code/modules/requisitions/supply_export.dm
  code/modules/xenomorph/_xeno_structure.dm
  code/modules/xenomorph/acidwell.dm
  code/modules/xenomorph/jellypod.dm
  code/modules/xenomorph/maw.dm
  code/modules/xenomorph/pherotower.dm
  code/modules/xenomorph/recovery_pylon.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/spawner.dm
  code/modules/xenomorph/trap.dm
  code/modules/xenomorph/tunnel.dm
  code/modules/xenomorph/xeno_turret.dm
  code/modules/xenomorph/xenoplant.dm
  code/modules/xenomorph/xenotowers.dm
Labels: Balance, Feature

#256 Nerf constant xeno healing in XvX
  code/__DEFINES/traits.dm
  code/_onclick/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance, Feature

#259 Edible jelly can be disposed off
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Feature

#262 Fixes corrupted minimap
  code/datums/jobs/job/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/acid_pools.dm
  code/modules/xenomorph/maw.dm
  code/modules/xenomorph/pherotower.dm
  code/modules/xenomorph/recovery_pylon.dm
  code/modules/xenomorph/resin_gargoyle.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/spawner.dm
  code/modules/xenomorph/tunnel.dm
  code/modules/xenomorph/xeno_turret.dm
Labels: Fix
