Repository EaglePhntm/NTFvsAlien, pull requests merged in 2025-05, with the labels that each got.

#233 Substract 160 errors
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/loadout.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/datums/components/jump.dm
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/icc.dm
  code/datums/jobs/job/other.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/datums/jobs/job/survivor.dm
  code/datums/jobs/job/vsd.dm
  code/datums/quick_load_outfits.dm
  code/datums/round_statistics.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/machinery/computer/intel_computer.dm
  code/game/objects/machinery/dropship_part_fabricator.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/structures/teleporter.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/vehicles/armored/tank_fabricator.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
  ntf_modular/code/_DEFINES/span.dm
  ntf_modular/code/datums/jobs/job/mothellian.dm
  ntf_modular/code/game/objects/machinery/computer/voucher.dm
  ntf_modular/code/modules/pixel_shift/code/pixel_shift.dm
  ntf_modular/code/modules/projectiles/guns/rifles.dm
  tgmc.dme
Labels: Removal, Fix

#238 KZ Weapon Adjustments
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/revolver_ammo.dm
  code/modules/projectiles/ammo_types/rifle_ammo.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/obj/items/ammo/pistol.dmi
  icons/obj/items/ammo/rifle.dmi
  icons/obj/items/items_mini.dmi
Labels: Fix, Balance, Feature

#239 KZ Weapon Adjustments Part 2
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance

#240 KZ Drip
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/under/marine_uniform.dm
Labels: Feature

#241 KZ PDW Vendor Addition
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#244 Armor and Clothing Additions
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/som_vending.dm
Labels: Feature, Merge Conflict
